# main.yml
name: print envs
on: push

jobs:
  build:
    name: print envs
    runs-on: ubuntu-latest    
    steps:
    - name: echo password
      run: echo $PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

